spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: bartek
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
    drop-first: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database:
    database-platform: org.hibernate.dialect.H2Dialect