spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:BookAlerts
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
    drop-first: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database:
    database-platform: org.hibernate.dialect.H2Dialect